task:
  name: "build"
  timeout_in: 40m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upload1
