#!/bin/bash
rm -rf scripts
mkdir fox-12.1
cd fox-12.1
export TZ="Asia/Dhaka"
sudo apt install git aria2 -y
git clone https://gitlab.com/OrangeFox/misc/scripts --depth=1
cd scripts       
sudo bash setup/android_build_env.sh
sudo bash setup/install_android_sdk.sh
cd -
mkdir OrangeFox_sync
cd OrangeFox_sync
git clone https://gitlab.com/OrangeFox/sync.git --depth=1
cd sync/
./orangefox_sync.sh --branch 12.1 --path ~/fox_12.1
cd ~/fox_12.1
git  clone -b stable https://github.com/ij-israfil/recovery_realme_RMX1901 device/realme/RMX1901
# build command
. build/envsetup.sh
lunch twrp_RMX1901-eng
mka adbd recoveryimage

# upload 
cd out/target/product/RMX1901
sudo wget https://raw.githubusercontent.com/ij-project/gofile-uploader/refs/heads/master/gofile -O "/usr/local/bin/gofile"; sudo chmod +x "/usr/local/bin/gofile"
gofile Orange*.zip
