#!/bin/bash
sync() {
mkdir -p ~/ROM
cd ~/ROM
git config --global user.name "ij_israfil"
git config --global user.email "israfilkhan494@gmail.com"
curl -LSs https://raw.githubusercontent.com/israfilbd/scripts/refs/heads/16/mistos.sh | bash
}

echo "Syncing Rom and Device Sources..."
sync
echo "Syncing"
echo "Syncing...."
echo "Syncing......Done"
